"""Add appointment_date and appointment_time

Revision ID: 1835c3927fd1
Revises: 3658a438834a
Create Date: 2025-11-11 16:02:15.585465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1835c3927fd1'
down_revision: Union[str, Sequence[str], None] = '3658a438834a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_date', sa.Date(), nullable=False))
    op.add_column('appointments', sa.Column('appointment_time', sa.Time(), nullable=False))
    op.add_column('appointments', sa.Column('fee', sa.Float(), nullable=True))
    op.add_column('appointments', sa.Column('status', sa.Enum('booked', 'cancelled', 'rescheduled', 'completed', name='appointmentstatus'), nullable=True))
    op.add_column('appointments', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'scheduled_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('appointments', 'notes')
    op.drop_column('appointments', 'status')
    op.drop_column('appointments', 'fee')
    op.drop_column('appointments', 'appointment_time')
    op.drop_column('appointments', 'appointment_date')
    # ### end Alembic commands ###
