"""Add name column to doctor_profiles

Revision ID: 357ac3cacdef
Revises: 1835c3927fd1
Create Date: 2025-11-11 18:49:50.281440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357ac3cacdef'
down_revision: Union[str, Sequence[str], None] = '1835c3927fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('doctor_profiles', sa.Column('degree', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_profiles', 'degree')
    op.drop_column('doctor_profiles', 'name')
    # ### end Alembic commands ###
