"""add gender column to users

Revision ID: 3658a438834a
Revises: 3d61da006edb
Create Date: 2025-11-11 15:00:58.949633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3658a438834a'
down_revision: Union[str, Sequence[str], None] = '3d61da006edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('scheduled_at', sa.DateTime(), nullable=False))
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('appointments', 'appointment_date')
    op.drop_column('appointments', 'notes')
    op.drop_column('appointments', 'status')
    op.drop_column('appointments', 'appointment_time')
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.add_column('appointments', sa.Column('appointment_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('status', postgresql.ENUM('BOOKED', 'CANCELLED', 'RESCHEDULED', 'COMPLETED', name='appointmentstatus'), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('appointment_date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'scheduled_at')
    # ### end Alembic commands ###
