"""fix doctor availability relationship

Revision ID: 70816fbccbb2
Revises: ad0f6466c75c
Create Date: 2025-11-10 19:23:29.012918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70816fbccbb2'
down_revision: Union[str, Sequence[str], None] = 'ad0f6466c75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'fee')
    op.drop_column('appointments', 'booking_time')
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_constraint(op.f('notifications_appointment_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'appointments', ['appointment_id'], ['id'])
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'updated_at')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('PATIENT', 'DOCTOR', 'ADMIN', name='userrole'),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PATIENT', 'DOCTOR', 'ADMIN', name='userrole'),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('notifications', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', postgresql.ENUM('EMAIL', 'SMS', 'IN_APP', name='notificationtype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notifications_appointment_id_fkey'), 'notifications', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notifications', 'is_read')
    op.add_column('appointments', sa.Column('booking_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
