"""fix notification-user relationship

Revision ID: ad0f6466c75c
Revises: e353a81d555d
Create Date: 2025-11-10 17:50:00.408171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad0f6466c75c'
down_revision: Union[str, Sequence[str], None] = 'e353a81d555d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('payment_status', sa.Enum('PAID', 'PENDING', 'NOT_REQUIRED', name='paymentstatus'), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_appointment_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'appointment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', postgresql.ENUM('EMAIL', 'SMS', 'IN_APP', name='notificationtype'), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_appointment_id_fkey'), 'notifications', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('notifications', 'is_read')
    op.drop_column('appointments', 'payment_status')
    # ### end Alembic commands ###
